artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shivdattaredekar/datasets/raw/main/UCI_Credit_Card.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/UCI_Credit_Card.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/UCI_Credit_Card.csv
  

model_trainer:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name : model.joblib
  scaler_name : scaler.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_training/model.joblib
  scaler_path: artifacts/model_training/scaler.joblib
  test_data_path: artifacts/data_transformation/test.csv
  metric_file_name: artifacts/model_evaluation/metrics.json
  


